export const PERMISSIONS = [
  "tickets.view",
  "tickets.reply",
  "tickets.assign",
  "tickets.close",
  "tickets.internal_note",
  "tickets.delete",
  "products.create",
  "products.edit",
  "products.obfuscate",
  "products.publish",
  "products.delete",
  "source_code.view",
  "source_code.upload",
  "licenses.view",
  "licenses.issue",
  "licenses.revoke",
  "licenses.extend",
  "credits.view",
  "credits.adjust",
  "topups.approve",
  "coupons.manage",
  "discounts.manage",
  "announcements.publish",
  "users.view",
  "users.manage",
  "roles.manage",
  "affiliates.manage",
  "webhooks.manage",
  "logs.view",
] as const

export type Permission = (typeof PERMISSIONS)[number]